### PR TITLE
Upgrade codebase to Swift 1.2

### PR DESCRIPTION
**Pull request by istx25**

### CODE REVIEW

**Comment by CodaFi** [comment]
Thanks for this!  Unfortunately I will not merge this until Travis gets their act together and updates to 1.2.

**Comment by istx25** [comment]
Okay, understandable! :smiley:

**Comment by CodaFi** [comment]
No, no, don't close this!  I will merge it, just not now.

**Comment by CodaFi** [comment]
I'll take you at your word that this builds.

:boat:

**Comment by istx25** [comment]
:smiley:

**Pull request merged**
