### PR TITLE
Swift 2.2

### PR DESCRIPTION
**Pull request by adamkuipers**
Updates project files to Xcode 7.3 recommended settings and changes `typealias` to `associatedtype`

---

This change is [Reviewable](https://reviewable.io/reviews/typelift/algebra/8)

### CODE REVIEW

**Comment by CodaFi** [comment]
Thanks!  Just bump the Xcode version in the Travis script and this should build.

**Comment by adamkuipers** [comment]
You know what could have caused the last failure? I'm not practiced enough with Travis to understand what "valid signing identities" it would be talking about.

**Comment by CodaFi** [comment]
Fuck, I don't know why it does this sometimes.  7.3 changed something or other about the build system so it randomly selects victims to require codesigning for where none was needed before (as in, Swiftz doesn't have this problem).

**Comment by CodaFi** [comment]
Try something for me please:
- Remove the build scripts folder
- Copy the build script out of Swiftz here
- `s/SwiftCheck/Algebra` in the manual calls to xcodebuild.

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
